config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :home, only: :index

  resources :customers, except: %i[index destroy]

  resources :products, only: %i[index show]

  resources :orders, only: :show
  get '/order_invoice', to: 'orders#invoice'
  get '/submit_order', to: 'orders#submit_order'

  # log in routes
  get    '/sign_in',   to: 'sessions#new'
  post   '/sign_in',   to: 'sessions#create'
  delete '/sign_out',  to: 'sessions#destroy'

  # contact and about us routes
  get '/contact_us', to: 'site_info#contact_us'
  get '/about_us', to: 'site_info#about_us'

  # shopping cart
  get '/shopping_cart', to: 'shopping_carts#index'
  post '/shopping_cart', to: 'shopping_carts#create'
  delete '/shopping_cart', to: 'shopping_carts#destroy'
  get '/increase_items_count_shopping_cart', to: 'shopping_carts#increase_items_count'
  get '/decrease_items_count_shopping_cart', to: 'shopping_carts#decrease_items_count'
end

app/views/layouts/header_content/_clothing_accessory_dropdown_menu.html.haml
%li.layout-dropdown
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    = g_header.upcase
  %ul.dropdown-menu
    %li.dropdown-header= "#{g_header}'s Clothing"
    %li= link_to Category::HOODIES, products_path(category_name: Category::HOODIES, gender: gender)
    %li= link_to Category::SWEATERS, products_path(category_name: Category::SWEATERS, gender: gender)
    %li= link_to Category::TOPS, products_path(category_name: Category::TOPS, gender: gender)
    %li= link_to Category::SHORTS, products_path(category_name: Category::SHORTS, gender: gender)
    %li= link_to Category::PANTS_AND_TIGHTS, products_path(category_name: Category::PANTS_AND_TIGHTS, gender: gender)
    %li= link_to Category::UNDERWEAR_AND_BASELAYER, products_path(category_name: Category::UNDERWEAR_AND_BASELAYER, gender: gender)
    %li.divider{:role => 'separator'}
    %li.dropdown-header= "#{g_header}'s Outdoor Accessories"
    %li= link_to Category::WINTER_GLOVES_AND_MITTS, products_path(category_name: Category::WINTER_GLOVES_AND_MITTS, gender: gender)
    %li= link_to Category::TOQUES_AND_BALACLAVAS, products_path(category_name: Category::TOQUES_AND_BALACLAVAS, gender: gender)
    %li= link_to Category::HATS_AND_CAPS, products_path(category_name: Category::HATS_AND_CAPS, gender: gender)
    %li.divider{:role => 'separator'}
    %li= link_to "All #{g_header}'s Clothing/Accessories", products_path(size_type: Product::CLOTHING_SIZE_TYPE, gender: gender)

app/views/layouts/header_content/_customer_options.html.haml
.dropdown#customer-option-list
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = current_customer.full_name
    %b.caret
  %ul.dropdown-menu
    %li
      = link_to customer_path(current_customer.id) do
        %i.fa.fa-user-circle-o
        Account
    %li.divider{:role => "separator"}
    %li
      = link_to sign_out_path, method: :delete do
        %i.fa.fa-sign-out
        Sign Out

app/views/layouts/header_content/_footwear_dropdown_menu.html.haml
%li.layout-dropdown
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    FOOTWEAR
  %ul.dropdown-menu
    %li.dropdown-header= "Men's Footwear"
    %li= link_to Category::HIKING_BOOTS, products_path(category_name: Category::HIKING_BOOTS, gender: Product::MALE)
    %li= link_to Category::WINTER_BOOTS, products_path(category_name: Category::WINTER_BOOTS, gender: Product::MALE)
    %li= link_to Category::HIKING_SHOES, products_path(category_name: Category::HIKING_SHOES, gender: Product::MALE)
    %li= link_to Category::RUNNING_SHOES, products_path(category_name: Category::RUNNING_SHOES, gender: Product::MALE)
    %li= link_to "All Men's Footwear", products_path(size_type: Product::FOOTWEAR_SIZE_TYPE, gender: Product::MALE)
    %li.divider{:role => 'separator'}
    %li.dropdown-header= "Women's Footwear"
    %li= link_to Category::HIKING_BOOTS, products_path(category_name: Category::HIKING_BOOTS, gender: Product::FEMALE)
    %li= link_to Category::WINTER_BOOTS, products_path(category_name: Category::WINTER_BOOTS, gender: Product::FEMALE)
    %li= link_to Category::HIKING_SHOES, products_path(category_name: Category::HIKING_SHOES, gender: Product::FEMALE)
    %li= link_to Category::RUNNING_SHOES, products_path(category_name: Category::RUNNING_SHOES, gender: Product::FEMALE)
    %li= link_to "All Women's Footwear", products_path(size_type: Product::FOOTWEAR_SIZE_TYPE, gender: Product::FEMALE)

app/views/layouts/header_content/_header.html.haml
%header
  = render partial: 'layouts/header_content/sign_in_plus_cart'
  = render partial: 'layouts/header_content/menu'

app/views/layouts/header_content/_menu.html.haml
%nav.navbar.navbar-default.navbar-custom
  .container
    .navbar-header
      %button.custom-navbar-burger.navbar-toggle.pull-left.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Crown Summit Outdoors', root_path, :class => 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        = render partial: 'layouts/header_content/clothing_accessory_dropdown_menu', locals: {gender: Product::MALE, g_header: 'Men'}
        = render partial: 'layouts/header_content/clothing_accessory_dropdown_menu', locals: {gender: Product::FEMALE, g_header: 'Women'}
        = render partial: 'layouts/header_content/footwear_dropdown_menu'
      = render partial: 'layouts/header_content/search_form'

app/views/layouts/header_content/_search_form.html.haml
= form_tag products_path, method: :get, class: 'navbar-form navbar-right' do
  .input-group.category-search-drop-down
    = select_tag :category_id, options_for_select(session[:search_categories], params[:category_id]), include_blank: 'All Categories', class: 'form-control'
  .input-group
    = text_field_tag :product_key_word, params[:product_key_word], class: 'form-control', placeholder: 'Search Products'
    %span.input-group-btn
      = button_tag type: :submit, class: 'btn btn-default' do
        %i.fa.fa-search

app/views/layouts/header_content/_sign_in_plus_cart.html.haml
.shop-sign-in-container
  .container
    .pull-left
      %p SITE DEMO
    .pull-right
      - if logged_in?
        = render partial: 'layouts/header_content/customer_options'
      - else
        = link_to 'Sign In / Create Account', sign_in_path, class: 'sign-in'
      #shopping-cart-preview
        = render partial: 'shopping_carts/preview'