config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :home, only: :index

  resources :customers, except: %i[index destroy]

  resources :products, only: %i[index show]

  resources :orders, only: :show
  get '/order_invoice', to: 'orders#invoice'
  get '/submit_order', to: 'orders#submit_order'

  # log in routes
  get    '/sign_in',   to: 'sessions#new'
  post   '/sign_in',   to: 'sessions#create'
  delete '/sign_out',  to: 'sessions#destroy'

  # contact and about us routes
  get '/contact_us', to: 'site_info#contact_us'
  get '/about_us', to: 'site_info#about_us'

  # shopping cart
  get '/shopping_cart', to: 'shopping_carts#index'
  post '/shopping_cart', to: 'shopping_carts#create'
  delete '/shopping_cart', to: 'shopping_carts#destroy'
  get '/increase_items_count_shopping_cart', to: 'shopping_carts#increase_items_count'
  get '/decrease_items_count_shopping_cart', to: 'shopping_carts#decrease_items_count'
end

app/controllers/shopping_carts_controller.rb
# this class lets you view, add, remove, and edit quantity of items in your cart
class ShoppingCartsController < ApplicationController
  # view items in your cart
  def index
    product_ids = session[:shopping_cart].keys.map(&:to_i)
    @products = Product.where(id: product_ids)
  end

  # add an item to your cart
  def create
    product_id = shopping_cart_params[:product_id]

    # ensure the product is not added to the cart twice
    return if session[:shopping_cart][product_id].present?

    session[:shopping_cart][product_id] = {
      quantity: shopping_cart_params[:quantity],
      size: shopping_cart_params[:size]
    }

    @product = Product.find(product_id.to_i)
  end

  # remove an item from your cart
  def destroy
    @product_id = params[:product_id].to_s

    # remove the item from the session
    session[:shopping_cart].delete(@product_id)

    calculate_order_total
  end

  # increase the quantity of an item in your cart
  def increase_items_count
    # ensure count cannot go above 5
    s_id = params[:product_id].to_s
    return if session[:shopping_cart][s_id]['quantity'].to_i >= 5

    session[:shopping_cart][s_id]['quantity'] =
      session[:shopping_cart][s_id]['quantity'].to_i + 1

    @product = Product.find(params[:product_id].to_i)
    calculate_order_total
  end

  # decrease the quantity of an item in your cart
  def decrease_items_count
    # ensure count cannot go below 1
    s_id = params[:product_id].to_s
    return if session[:shopping_cart][s_id]['quantity'].to_i <= 1

    session[:shopping_cart][s_id]['quantity'] =
      session[:shopping_cart][s_id]['quantity'].to_i - 1

    @product = Product.find(params[:product_id].to_i)
    calculate_order_total
  end

  private

  def shopping_cart_params
    params.require(:shopping_cart).permit(:product_id, :quantity, :size)
  end

  def calculate_order_total
    # recalculate the order total
    @order_total = 0
    products_ids = session[:shopping_cart].keys.map(&:to_i)
    Product.where(id: products_ids).each do |p|
      @order_total += p.price * session[:shopping_cart][p.id.to_s]['quantity'].to_f
    end
  end

end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
  def shopping_cart_count
    session[:shopping_cart].count
  end
end

app/views/shopping_carts/_cart_header_fields.html.haml
.well#summary-items-header
  .row
    .col-md-7.col-sm-7.col-xs-12
      ITEM(S)
    .col-md-1.col-sm-1.hidden-xs
      QTY
    .col-md-2.col-sm-2.hidden-xs
      PRICE
    .col-md-2.col-sm-2.hidden-xs
      TOTAL

app/views/shopping_carts/_cart_item.html.haml
- cart_item = session[:shopping_cart][product.id.to_s]

.summary-item-container
  .row
    .col-md-7.col-sm-7.col-xs-12
      .row
        .col-md-5.col-sm-5.col-xs-12
          = link_to product_path(id: product.id), class: 'inline-block' do
            = image_tag "#{product.image}", class: 'image-size-mid'
        .col-md-7.col-sm-7.col-xs-12
          %h5= link_to product.name, product_path(id: product.id)
          %h5
            Size:
            = cart_item['size']

    .col-md-1.col-sm-1.col-xs-4
      %h5.inline.hidden-md.hidden-sm.hidden-lg Qty:
      %h5.inline.hidden-md.hidden-sm.hidden-lg= cart_item['quantity']
      %h5.hidden-xs= cart_item['quantity']

      .col-md-12.col-xs-12.item-count-links
        = link_to decrease_items_count_shopping_cart_path(product_id: product.id), title: 'Decrease item count', remote: true do
          %i.fa.fa-minus
        = link_to increase_items_count_shopping_cart_path(product_id: product.id), title: 'Increase item count', remote: true do
          %i.fa.fa-plus

    .col-md-2.col-sm-2.col-xs-6.hidden-xs
      %h5= currency(product.price)

    .col-md-2.col-sm-2.col-xs-6.hidden-xs
      %h5= currency((product.price * cart_item['quantity'].to_f))

    .col-md-2.col-sm-2.col-xs-8.hidden-sm.hidden-md.hidden-lg
      .block
        %h5.inline.hidden-md.hidden-sm.hidden-lg Price:
        %h5.inline= currency(product.price)
      .block
        %h5.inline.hidden-md.hidden-sm.hidden-lg Total:
        %h5.inline= currency((product.price * cart_item['quantity'].to_f))

  = link_to shopping_cart_path(product_id: product.id), method: :delete, class: 'remove-cart-item', title: 'Remove item from cart', remote: true, data: { confirm: 'Are you sure you want to remove this item from your cart?' } do
    %i.fa.fa-times

app/views/shopping_carts/_form.html.haml
- cart_contains_item = session[:shopping_cart][product.id.to_s].present?
= form_for :shopping_cart, url: shopping_cart_path, html: { class: 'form form-horizontal', remote: true } do |f|
  .row
    = hidden_field_tag 'shopping_cart[product_id]', product.id
    .col-xs-12.col-md-6
      .form-group
        %label.control-label Size:
        = f.select :size, product.size_type == clothing_type ? clothing_size_options : footwear_size_options, {}, {class: 'form-control option-drop-down-left', disabled: cart_contains_item}
    .col-xs-12.col-md-6
      .form-group
        %label.control-label Quantity:
        = f.select :quantity, quantity_options, {}, {class: 'form-control', disabled: cart_contains_item}
  .form-group
    = button_tag type: :submit, class: 'btn btn-success', id: 'add-to-cart', disabled: cart_contains_item do
      %i.fa.fa-plus
      ADD TO CART
    - if cart_contains_item
      %p.item-already-added-warning You have already added this item to your cart *

app/views/shopping_carts/_order_summary.html.haml
.panel.panel-default.order-summary-panel
  .panel-heading
    %h3.bold
      %i.fa.fa-shopping-cart
      Order Summary
  .panel-body
    .row
      .col-md-12
        %h4.pull-left= 'Estimated Total:'
        %h4.pull-right= currency(order_total)
    %hr
    .row
      .col-md-12
        %h5.pull-left= 'Merchandise Subtotal:'
        %h5.pull-right= currency(order_total)
    %hr
    .row
      .col-md-12
        %h5.pull-left= 'Merchandise Savings:'
        %h5.pull-right= '$0.00'

- if order_total <= 0
  %btn.btn.btn-danger.btn-lg#checkout-cart{disabled: true}
    Your cart appears to be empty
    🙁
- elsif !logged_in?
  %btn.btn.btn-warning.btn-lg#checkout-cart{disabled: true} Please sign in to Checkout
- else
  = link_to order_invoice_path, class: 'btn btn-success btn-lg', id: 'checkout-cart' do
    %i.fa.fa-lock
    Checkout

app/views/shopping_carts/_preview.html.haml
= link_to shopping_cart_path, class: 'inline-block' do
  %i.fa.fa-shopping-cart.fa-lg
  %span.cart-item-count= shopping_cart_count
  %span ITEM(S)

app/views/shopping_carts/create.js.erb
$('#shopping-cart-preview').html("<%= j render partial: 'shopping_carts/preview' %>");
$('#add-item-to-cart-form').html("<%= j render partial: 'shopping_carts/form', locals: { product: @product } %>")

app/views/shopping_carts/decrease_items_count.js.erb
$('#cart-item-<%= @product.id %>').html("<%= j render partial: 'shopping_carts/cart_item', locals: { product: @product } %>");
$('#cart-order-summary').html("<%= j render partial: 'shopping_carts/order_summary', locals: { order_total: @order_total.round(2)} %>")

app/views/shopping_carts/destroy.js.erb
$('#shopping-cart-preview').html("<%= j render partial: 'shopping_carts/preview' %>");
$('#cart-item-<%= @product_id %>').remove();
$('#cart-order-summary').html("<%= j render partial: 'shopping_carts/order_summary', locals: { order_total: @order_total.round(2)} %>")

app/views/shopping_carts/increase_items_count.js.erb
$('#cart-item-<%= @product.id %>').html("<%= j render partial: 'shopping_carts/cart_item', locals: { product: @product } %>");
$('#cart-order-summary').html("<%= j render partial: 'shopping_carts/order_summary', locals: { order_total: @order_total.round(2)} %>")

app/views/shopping_carts/index.html.haml
%h2 Shopping Cart

%hr

- if @products.present?
  - order_total = 0
  - @products.each { |p| order_total+= (p.price * session[:shopping_cart][p.id.to_s]['quantity'].to_f) }
  .row
    .col-md-8
      = render partial: 'shopping_carts/cart_header_fields'
      - @products.each do |product|
        .div{id: "cart-item-#{product.id}"}
          = render partial: 'shopping_carts/cart_item', locals: { product: product }
    .col-md-4
      #cart-order-summary
        = render partial: 'shopping_carts/order_summary', locals: { order_total: order_total.round(2) }
- else
  %h4
    Your cart appears to be empty.
    🙁