config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :home, only: :index

  resources :customers, except: %i[index destroy]

  resources :products, only: %i[index show]

  resources :orders, only: :show
  get '/order_invoice', to: 'orders#invoice'
  get '/submit_order', to: 'orders#submit_order'

  # log in routes
  get    '/sign_in',   to: 'sessions#new'
  post   '/sign_in',   to: 'sessions#create'
  delete '/sign_out',  to: 'sessions#destroy'

  # contact and about us routes
  get '/contact_us', to: 'site_info#contact_us'
  get '/about_us', to: 'site_info#about_us'

  # shopping cart
  get '/shopping_cart', to: 'shopping_carts#index'
  post '/shopping_cart', to: 'shopping_carts#create'
  delete '/shopping_cart', to: 'shopping_carts#destroy'
  get '/increase_items_count_shopping_cart', to: 'shopping_carts#increase_items_count'
  get '/decrease_items_count_shopping_cart', to: 'shopping_carts#decrease_items_count'
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password

  belongs_to :country, inverse_of: :customers
  belongs_to :province, inverse_of: :customers
  has_many :orders, inverse_of: :customer, dependent: :restrict_with_error

  validates_presence_of :first_name, :last_name, :address, :postal_code, :email,
                        :country_id, :province_id, :city
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  validates_length_of :password, minimum: 8, on: :update, if: :password
  validates_uniqueness_of :email, message: 'already in use'
  validates_format_of :email,
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
                      message: 'must be a valid email address'

  def full_name
    "#{first_name} #{last_name}"
  end

  def recent_orders
    orders.includes(:order_items).where('created_at >= ?', 2.weeks.ago).order(created_at: :desc)
  end
end

app/controllers/customers_controller.rb
# Lets customers manage their user accounts
class CustomersController < ApplicationController
  include SessionsHelper
  before_action :load_countries_and_provinces, except: :show
  before_action :check_if_logged_in, only: %i[show edit update]

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save!
    session[:customer_id] = @customer.id
    flash.now[:notice] = 'Account created successfully'
    render :show
  rescue ActiveRecord::RecordInvalid => error
    flash.now[:error] = error.message
    render :new
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update_attributes!(customer_params)
    flash.now[:notice] = 'Account information updated successfully'
    render :show
  rescue ActiveRecord::RecordInvalid => error
    flash.now[:error] = error.message
    render :edit
  end

  protected

  def customer_params
    params.require(:customer).permit(
      :first_name, :last_name, :address, :postal_code, :email, :password,
      :password_confirmation, :country_id, :province_id, :city
    )
  end

  def load_countries_and_provinces
    @countries = Country.order(:name).map { |c| [c.name, c.id] }
    @provinces = Province.order(:name).map { |p| [p.name, p.id] }
  end

  def check_if_logged_in
    unless logged_in? && (params[:id].to_i == current_customer.id)
      flash[:error] = 'Unauthorized, please login'
      redirect_to home_index_path
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for @customer, html: { class: 'form form-horizontal' } do |f|
      .form-group
        %label.control-label.col-md-3 First Name:
        .col-md-9
          = f.text_field :first_name, class: 'form-control', autofocus: true

      .form-group
        %label.control-label.col-md-3 Last Name:
        .col-md-9
          = f.text_field :last_name, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Country:
        .col-md-9
          = f.select :country_id, @countries, {prompt: 'Please select a country'}, {class: 'form-control'}

      .form-group
        %label.control-label.col-md-3 Province:
        .col-md-9
          = f.select :province_id, @provinces, {prompt: 'Please select a province'}, {class: 'form-control'}

      .form-group
        %label.control-label.col-md-3 City:
        .col-md-9
          = f.text_field :city, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Address:
        .col-md-9
          = f.text_field :address, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Postal Code:
        .col-md-9
          = f.text_field :postal_code, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Email:
        .col-md-9
          = f.text_field :email, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Password:
        .col-md-9
          = f.password_field :password, class: 'form-control'

      .form-group
        %label.control-label.col-md-3 Password Confirmation:
        .col-md-9
          = f.password_field :password_confirmation, class: 'form-control'

      .form-group
        .pull-right
          .customer-btn-group
            = button_tag type: :submit, class: 'btn btn-primary btn-md' do
              %i.fa.fa-share
              = @customer.new_record? ? 'Submit' : 'Update'

            = link_to @customer.new_record? ? home_index_path : @customer, class: 'btn btn-default btn-md' do
              %i.fa.fa-ban
              Cancel

app/views/customers/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h2 Edit Account Details
    %hr
= render partial: 'customers/form'

app/views/customers/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h2 New Account Details
    %hr
= render partial: 'customers/form'

app/views/customers/show.html.haml
.row
  .col-md-4.col-sm-4.col-xs-12
    %h3
      Account Details
      = link_to edit_customer_path(id: @customer.id), id: 'account-details-edit-link' do
        %i.fa.fa-edit
        Edit
    %hr
    .row
      .col-md-4.col-sm-4.col-xs-12
        %p
          %strong Email:
      .col-md-8.col-sm-8.col-xs-12
        = @customer.email

    .row
      .col-md-4.col-sm-4.col-xs-12
        %p
          %strong Address:
      .col-md-8.col-sm-8.col-xs-12
        %address
          = "#{@customer.first_name} #{@customer.last_name}"
          %br
          = @customer.address
          %br
          = "#{@customer.city}, #{@customer.province.name} #{@customer.postal_code}"
          %br
          = @customer.country.name
  .col-md-8.col-sm-8.col-xs-12
    %h3 Recent Orders
    %hr

    - if @customer.recent_orders.present?
      %table.table.table-striped
        %thead
          %tr
            %th Order No
            %th Status
            %th Updated
        %tbody
          - @customer.recent_orders.each do |order|
            %tr
              %td= link_to order.order_no, order_path(id: order.id)
              %td= order.status.title
              %td= order.updated_at.strftime('%b %d, %Y')
    - else
      %h5 You have not placed any orders in the past 2 weeks.