config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :home, only: :index

  resources :customers, except: %i[index destroy]

  resources :products, only: %i[index show]

  resources :orders, only: :show
  get '/order_invoice', to: 'orders#invoice'
  get '/submit_order', to: 'orders#submit_order'

  # log in routes
  get    '/sign_in',   to: 'sessions#new'
  post   '/sign_in',   to: 'sessions#create'
  delete '/sign_out',  to: 'sessions#destroy'

  # contact and about us routes
  get '/contact_us', to: 'site_info#contact_us'
  get '/about_us', to: 'site_info#about_us'

  # shopping cart
  get '/shopping_cart', to: 'shopping_carts#index'
  post '/shopping_cart', to: 'shopping_carts#create'
  delete '/shopping_cart', to: 'shopping_carts#destroy'
  get '/increase_items_count_shopping_cart', to: 'shopping_carts#increase_items_count'
  get '/decrease_items_count_shopping_cart', to: 'shopping_carts#decrease_items_count'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, inverse_of: :orders
  belongs_to :status, inverse_of: :orders
  has_many :order_items, inverse_of: :order, dependent: :restrict_with_error

  validates_presence_of :pst_rate, :gst_rate, :hst_rate,
                        :status, :customer, :order_no
end

app/controllers/orders_controller.rb
# used to process orders
class OrdersController < ApplicationController
  include SessionsHelper
  before_action :check_if_logged_in, only: %i[show invoice submit_order]

  def show
    @order = Order.find(params[:id])

    # ensure the order belongs to the customer trying to look at it
    order_belongs_to_customer?(@order)

    calculate_costs(@order)
  end

  def invoice
    load_order_info
  end

  def submit_order
    load_order_info

    # create the order for the customer
    order = create_order

    # add items to the order based off what is in the cart
    add_order_items(order, @products)

    # now empty the cart since the order has been submitted
    session[:shopping_cart] = {}
  end

  protected

  def check_if_logged_in
    unless logged_in?
      flash[:error] = 'Unauthorized, please login'
      redirect_to home_index_path
    end
  end

  private

  def calculate_costs(order)
    subtotal = 0
    order.order_items.each { |i| subtotal += (i.price * i.quantity.to_f) }

    pst_cost = (order.pst_rate * subtotal).round(2)
    gst_cost = (order.gst_rate * subtotal).round(2)
    hst_cost = (order.hst_rate * subtotal).round(2)
    total = subtotal + pst_cost + gst_cost + hst_cost

    @costs = { pst_cost: pst_cost, gst_cost: gst_cost, hst_cost: hst_cost,
               subtotal: subtotal.round(2), total: total.round(2) }
  end

  def order_belongs_to_customer?(order)
    unless order.customer_id == current_customer.id
      flash[:error] = 'Unauthorized, please login'
      redirect_to home_index_path
    end
  end

  def load_clean_cart
    @cart = {}

    # convert the carts values to the correct data types
    session[:shopping_cart].each_pair do |k, v|
      @cart.store(k.to_i, quantity: v['quantity'].to_i, size: v['size'])
    end
  end

  def load_order_info
    load_clean_cart
    @products = Product.where(id: @cart.keys)
  end

  def create_order
    status_id = Status.processing.id
    province = current_customer.province

    current_customer.orders.create!(
      pst_rate: province.pst,
      gst_rate: province.gst,
      hst_rate: province.hst,
      status_id: status_id,
      order_no: (1_000_000_000 + Random.rand(10_000_000_000 - 1_000_000_000))
    )
  end

  def add_order_items(order, products)
    # create an order item for each of the products in the cart
    products.each do |product|
      order.order_items.create!(
        quantity: @cart[product.id][:quantity],
        price: product.price,
        product_id: product.id,
        size: @cart[product.id][:size]
      )
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  # returns a has containing the orders cost information
  def calculate_order_costs(products, cart)
    subtotal = 0
    products.each { |p| subtotal += (p.price * cart[p.id][:quantity].to_f) }

    pst_cost = (current_customer.province.pst * subtotal).round(2)
    gst_cost = (current_customer.province.gst * subtotal).round(2)
    hst_cost = (current_customer.province.hst * subtotal).round(2)
    total = subtotal + pst_cost + gst_cost + hst_cost

    { pst_cost: pst_cost, gst_cost: gst_cost, hst_cost: hst_cost,
      subtotal: subtotal.round(2), total: total.round(2) }
  end
end

app/views/orders/_order_total.html.haml
.panel.panel-default.order-summary-panel
  .panel-heading
    %h3.bold
      - if already_submitted
        %i.fa.fa-shopping-bag
        Details
      - else
        %i.fa.fa-shopping-cart
        Order Summary
  .panel-body
    - if already_submitted
      .row
        .col-md-12
          %h5.pull-left= 'Status:'
          %h5.pull-right= status
      %hr
    .row
      .col-md-12
        %h5.pull-left= 'Subtotal:'
        %h5.pull-right= currency(details[:subtotal])
    %hr
    - unless details[:pst_cost].zero?
      .row
        .col-md-12
          %h5.pull-left= 'PST:'
          %h5.pull-right= currency(details[:pst_cost])
      %hr
    - unless details[:gst_cost].zero?
      .row
        .col-md-12
          %h5.pull-left= 'GST:'
          %h5.pull-right= currency(details[:gst_cost])
      %hr
    - unless details[:hst_cost].zero?
      .row
        .col-md-12
          %h5.pull-left= 'HST:'
          %h5.pull-right= currency(details[:hst_cost])
      %hr
    .row
      .col-md-12
        %h5.pull-left= 'Merchandise Savings:'
        %h5.pull-right= '$0.00'
    %hr
    .row
      .col-md-12
        %h5.pull-left= 'Shipping Charges:'
        %h5.pull-right= '$0.00'

  .panel-footer
    .row
      .col-md-12
        .order-total
          %h4.pull-left= already_submitted ? 'Total:' : 'Order Total:'
          %h4.pull-right= currency(details[:total])

- unless already_submitted
  = link_to submit_order_path, class: 'btn btn-success btn-lg', id: 'checkout-cart' do
    %i.fa.fa-lock
    Submit Order

app/views/orders/invoice.html.haml
%h2 Order Invoice
%hr

.row
  .col-md-8
    %h3= "Shipping Information for #{current_customer.full_name}"
    %address
      %strong= current_customer.address
      %br
      %strong= "#{current_customer.city}, #{current_customer.province.name} #{current_customer.postal_code}"
      %br
      %strong= current_customer.country.name

    %hr

    %h3 Order Items
    %table.table.table-striped
      %thead
        %tr.row
          %th Product
          %th
          %th Qty
          %th Price
          %th Total
      %tbody
        - @products.each do |product|

          %tr.row
            %td.col-md-2.col-sm-2.col-xs-2
              = image_tag "#{product.image}", class: 'image-size-min'
            %td.col-md-5.col-sm-5.col-xs-5
              %h5
                = product.name
                = @cart[product.id][:size]
            %td.col-md-1.col-sm-1.col-xs-1
              %h5= @cart[product.id][:quantity]
            %td.col-md-2.col-sm-2.col-xs-2
              %h5= currency(product.price)
            %td.col-md-2.col-sm-2.col-xs-2
              %h5= currency((product.price * @cart[product.id][:quantity].to_f))



  .col-md-4
    #cart-order-summary
      = render partial: 'orders/order_total', locals: { details: calculate_order_costs(@products, @cart), already_submitted: false }

app/views/orders/show.html.haml
%h2
  = "Order ##{@order.order_no}"
  = link_to customer_path(id: current_customer.id), class: 'header-link pull-right' do
    %i.fa.fa-caret-left
    Back
%hr

.row
  .col-md-8
    %h3 Items
    %table.table.table-striped
      %thead
        %tr.row
          %th Product
          %th
          %th Qty
          %th Price
          %th Total
      %tbody
        - @order.order_items.each do |item|
          %tr.row
            %td.col-md-2.col-sm-2.col-xs-2
              = image_tag "#{item.product.image}", class: 'image-size-min'
            %td.col-md-5.col-sm-5.col-xs-5
              %h5
                = item.product.name
                = item.size
            %td.col-md-1.col-sm-1.col-xs-1
              %h5= item.quantity
            %td.col-md-2.col-sm-2.col-xs-2
              %h5= currency(item.price)
            %td.col-md-2.col-sm-2.col-xs-2
              %h5= currency((item.price * item.quantity.to_f))
  .col-md-4
    = render partial: 'orders/order_total', locals: { details: @costs, already_submitted: true, status: @order.status.title }

app/views/orders/submit_order.html.haml
%h2 Your Order Has Been Submitted
%hr
%h5 Your orders status can be viewed on the account page.